apiVersion: v1
kind: Service
metadata:
  name: canary-service
  namespace: argo-rollouts
spec:
  selector:
    app: canary-app
  ports:
    - protocol: TCP
      port: 80       # Service port
      targetPort: 3000  # Container port
  type: ClusterIP
